### PR TITLE
Fix more secure crypto comment

### PR DESCRIPTION
**Pull request by fritz-c**
Without conversion to a string, I'm pretty sure the result of `pbkdf2Sync` is binary data. At any rate, it was failing until I added on `toString('base64')`.

### CODE REVIEW

**Comment by ealeksandrov** [comment]
Thanks! Please update this to use url-safe encoding:
http://stackoverflow.com/questions/8855687/secure-random-token-in-node-js
and I will merge it in.

**Comment by fritz-c** [comment]
@ealeksandrov Fixed!

**Comment by ealeksandrov** [comment]
Why don't you choose more elegant `toString('hex')`? :)

**Comment by fritz-c** [comment]
I figured storing a hexadecimal string as a string in the database would be a waste of space, but after checking it, the size of the base64-encoded string wasn't as different from the hex one as I thought. I'll change it to hex.

**Comment by ealeksandrov** [comment]
Great! Thanks a lot for all your contributions!

**Comment by fritz-c** [comment]
No problem!

**Pull request merged**
